version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data

  dbt:
    image: python:3.9-slim
    command: tail -f /dev/null
    volumes:
      - ./dbt_project:/dbt
    depends_on:
      - minio
    entrypoint: >
      /bin/bash -c "pip install dbt-core dbt-duckdb duckdb==0.9.2 && dbt --version && /bin/bash"

volumes:
  minio-data: